### ISSUE TITLE
La belle forêt

### ISSUE THREAD

**Issue by pellem** [Ethiraric/createMakefile#2]
Salut,
Plutot que ta forêt de "if", "elif" plutot conséquente, tu devrais te pencher sur l'utilisation (très simple) de la librairie argparse.

def get_arguments():
    """
    Commente ta fonction
    """
    import argparse

```
parser = argparse.ArgumentParser(description='blabla')
parser.add_argument("-p", "--Path", type=str, default=".", help="Path of your folder")
parser.add_argument('--version', action='version', version='%(prog)s 0.1 (alpha)')
result = parser.parse_args()
args = dict(result._get_kwargs())
return args
```

Tu peux ajouter autant d'arguments que tu le souhaites grâce à parser.add_argument, en rendre certain obligatoires, affecter une valeur par défaut à d'autres...

J'ai fait en sorte que ça te retourne un dictionnaire, plus simple à utiliser par la suite. Tu auras un code plus lisible. En plus ça te génère le --help tout seul !

Bon courage, et bon travail, c'est cool !

**Comment by Ethiraric** [comment]
Salut,

J'avais prévu de faire ça (le TODO à la ligne 9).
Je bosse très rarement avec Python, j'ai pas les bons réflexes.
J'essaierai d'y regarder dans la semaine si j'ai le temps.

Merci du feedback ;)
